package com.example.java_video.ui.theme

import androidx.compose.ui.graphics.Color

// A palette of bold neutrals with an electric accent.
// Accent color.

val md_theme_light_primary = Color(0xFF111111)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF1E1E1E)
val md_theme_light_onPrimaryContainer = Color(0xFFF5F5F5)
val md_theme_light_secondary = Color(0xFFB6FF00)
val md_theme_light_onSecondary = Color(0xFF111111)
val md_theme_light_secondaryContainer = Color(0xFFE8FF8C)
val md_theme_light_onSecondaryContainer = Color(0xFF111111)
val md_theme_light_tertiary = Color(0xFF3D3D3D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEAEAEA)
val md_theme_light_onTertiaryContainer = Color(0xFF111111)
val md_theme_light_error = Color(0xFFDA1E28)
val md_theme_light_errorContainer = Color(0xFFFFD7D7)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410003)
val md_theme_light_background = Color(0xFFF6F6F6)
val md_theme_light_onBackground = Color(0xFF111111)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF111111)
val md_theme_light_surfaceVariant = Color(0xFFE4E4E4)
val md_theme_light_onSurfaceVariant = Color(0xFF3F3F3F)
val md_theme_light_outline = Color(0xFF757575)
val md_theme_light_inverseOnSurface = Color(0xFF0A0A0A)
val md_theme_light_inverseSurface = Color(0xFF2B2B2B)
val md_theme_light_inversePrimary = Color(0xFFE4FF7A)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = md_theme_light_secondary
val md_theme_light_outlineVariant = Color(0xFFC7C7C7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB6FF00)
val md_theme_dark_onPrimary = Color(0xFF101C00)
val md_theme_dark_primaryContainer = Color(0xFF2C4000)
val md_theme_dark_onPrimaryContainer = Color(0xFFE8FF8C)
val md_theme_dark_secondary = Color(0xFFFFFFFF)
val md_theme_dark_onSecondary = Color(0xFF101010)
val md_theme_dark_secondaryContainer = Color(0xFF1E1E1E)
val md_theme_dark_onSecondaryContainer = Color(0xFFEDEDED)
val md_theme_dark_tertiary = Color(0xFFE4E4E4)
val md_theme_dark_onTertiary = Color(0xFF161616)
val md_theme_dark_tertiaryContainer = Color(0xFF2A2A2A)
val md_theme_dark_onTertiaryContainer = Color(0xFFEAEAEA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF050505)
val md_theme_dark_onBackground = Color(0xFFEAEAEA)
val md_theme_dark_surface = Color(0xFF0F0F0F)
val md_theme_dark_onSurface = Color(0xFFEAEAEA)
val md_theme_dark_surfaceVariant = Color(0xFF303030)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C7C7)
val md_theme_dark_outline = Color(0xFF8F8F8F)
val md_theme_dark_inverseOnSurface = Color(0xFF050505)
val md_theme_dark_inverseSurface = Color(0xFFEAEAEA)
val md_theme_dark_inversePrimary = Color(0xFF203200)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = md_theme_dark_primary
val md_theme_dark_outlineVariant = Color(0xFF4A4A4A)
val md_theme_dark_scrim = Color(0xFF000000)

